remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
title: [React Tic-Tac-Toe Game]
name: [React Tic-Tac-Toe Game]
description: [Built learning the basics of ReactJS]
show_downloads: [false]
google_analytics: [Your Google Analytics tracking ID]
